### ISSUE TITLE
Could API-call "version" also list version of zonemaster

### ISSUE THREAD

**Issue by einar** [jelu/lim-plugin-zonalizer#1]
"GET /zonalizer/1/version" <--- could this one also give output similar to "zonemaster-cli --version"? Would make it much easier (and more light weight) to retrieve version numbers of "everything" for the Frontend & other uses.

**Comment by jelu** [comment]
Of course, how about https://github.com/jelu/lim-plugin-zonalizer/commit/d22d1107a4bb7d0b6fb263f022c65b96690dbd6e ?

**Comment by einar** [comment]
Works fine, thanks! :]
